import {
  ArrowDownLeft, ArrowUpRight, BarChart3, Bell, Check, ChevronRight, CircleAlert, CircleDollarSign,
  CreditCard, Edit3, LayoutDashboard, Menu, MessageCircle, Plus, Receipt, Send,
  Settings2, Sparkles, Trash2, TrendingUp, WalletCards, X,
} from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";

type Kind = "income" | "expense" | "bill";
type View = "overview" | "transactions" | "settings";
type Item = { id: number; kind: Kind; amountCents: number; merchant: string; category: string; entryDate: string; isFixed: boolean; paymentMethod?: string; isPlanned?: boolean; scheduledDay?: number };
type Message = { id: number; role: "user" | "assistant"; content: string };
type Profile = { monthlyIncomeCents: number; savingsGoalCents: number; incomeByMonth?: Record<string, number>; salarySchedule?: { amountCents: number; day: number; nextDue: string } };
type EditItem = Item;

const STORAGE_KEY = "bolso-claro-local-v1";
const MONTH_NAMES = ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"];
const categoryColors: Record<string, string> = { Lazer: "#C9A06A", "Farmácia": "#8E7BB5", Comida: "#E07A5F", Mercado: "#71A68A", Transporte: "#6B8FC4", Moradia: "#A77E66", Saúde: "#C77788", Educação: "#5C9DA1", Assinaturas: "#8A8AB7", "Cuidados pessoais": "#D68EAE", Outros: "#9BA5A0" };
const categories = Object.keys(categoryColors);
const paymentMethods = ["Pix", "Crédito", "Débito", "Dinheiro"];
const logoUrl = `${import.meta.env.BASE_URL}bolso-claro-logo.svg`;

function localDate(offsetDays = 0) {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() + offsetDays);
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
}
function today() { return localDate(); }
function dateLabel(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR", { day: "2-digit", month: "short" }).replace(" de ", " "); }
function dateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function nextMonthDate(value: string, day: number) { const date = new Date(`${value}T12:00:00`); date.setDate(1); date.setMonth(date.getMonth() + 1); const lastDay = new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate(); date.setDate(Math.min(day, lastDay)); return dateKey(date); }
function scheduleFromText(text: string) {
  const lower = text.toLowerCase();
  if (lower.includes("depois de amanhã") || lower.includes("depois de amanha")) return { entryDate: localDate(2), isPlanned: true, scheduledDay: undefined };
  if (lower.includes("amanhã") || lower.includes("amanha")) return { entryDate: localDate(1), isPlanned: true, scheduledDay: undefined };
  const dateMatch = lower.match(/\b(?:dia|em)\s*(\d{1,2})(?:\/(\d{1,2}))?\b/);
  if (dateMatch) {
    const now = new Date();
    const requestedDay = Math.min(31, Number(dateMatch[1]));
    const hasExplicitMonth = Boolean(dateMatch[2]);
    const month = hasExplicitMonth ? Number(dateMatch[2]) : now.getMonth() + 1 + (requestedDay <= now.getDate() ? 1 : 0);
    const lastDay = new Date(now.getFullYear(), month, 0).getDate();
    const date = new Date(now.getFullYear(), month - 1, Math.min(requestedDay, lastDay), 12);
    return { entryDate: dateKey(date), isPlanned: true, scheduledDay: requestedDay };
  }
  return { entryDate: today(), isPlanned: false, scheduledDay: undefined };
}
function money(cents = 0) { return (cents / 100).toLocaleString("pt-BR", { style: "currency", currency: "BRL" }); }
function parseMoney(value: string) { return Math.round(Number(value.replace(/\./g, "").replace(",", ".")) * 100) || 0; }
function shortDate(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString("pt-BR", { day: "2-digit", month: "short" }).replace(" de ", " "); }
function initials(name = "Você") { return name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase(); }
function monthLabel() { const now = new Date(); return `${MONTH_NAMES[now.getMonth()]} ${now.getFullYear()}`; }
function currentMonthKey() { return today().slice(0, 7); }
function greeting() { const hour = new Date().getHours(); return hour < 6 ? "Boa madrugada" : hour < 12 ? "Bom dia" : hour < 18 ? "Boa tarde" : "Boa noite"; }
function isMonthClosing() { const now = new Date(); return now.getDate() >= new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate() - 2; }
function readStore() { try { const raw = localStorage.getItem(STORAGE_KEY); return raw ? JSON.parse(raw) : null; } catch { return null; } }
function saveStore(data: { items: Item[]; messages: Message[]; profile: Profile }) { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); }

function parseText(text: string): Omit<Item, "id"> | null {
  const match = text.match(/(?:r\$\s*)?(\d{1,3}(?:\.\d{3})*(?:,\d{1,2})?|\d+(?:[.,]\d{1,2})?)/i);
  if (!match) return null;
  const amountCents = parseMoney(match[1]);
  if (!amountCents) return null;
  const lower = text.toLowerCase();
  const kind: Kind = /\b(recebi|ganhei|salário|salario|renda|entrada|receita)\b/.test(lower) ? "income" : /\b(conta|boleto|vence|vencimento)\b/.test(lower) ? "bill" : "expense";
  const keywords: Record<string, string[]> = { Mercado: ["mercado", "supermercado", "feira"], Comida: ["almoço", "almoco", "jantar", "café", "cafe", "ifood", "pizza", "lanche", "restaurante"], Transporte: ["uber", "99", "gasolina", "ônibus", "onibus", "metrô", "metro"], Moradia: ["aluguel", "luz", "água", "agua", "internet", "casa"], Farmácia: ["farmácia", "farmacia", "remédio", "remedio"], Lazer: ["shopping", "cinema", "viagem", "bar", "show"], Saúde: ["médico", "medico", "dentista", "exame"], Assinaturas: ["netflix", "spotify", "prime", "assinatura"], "Cuidados pessoais": ["academia", "barbearia", "salão", "salao"], Educação: ["curso", "livro", "escola"] };
  const category = kind === "income" ? "Renda" : Object.entries(keywords).find(([, words]) => words.some((word) => lower.includes(word)))?.[0] || "Outros";
  const paymentMethod = lower.includes("pix") ? "Pix" : lower.includes("crédito") || lower.includes("credito") || lower.includes("cartão") || lower.includes("cartao") ? "Crédito" : lower.includes("débito") || lower.includes("debito") ? "Débito" : lower.includes("dinheiro") || lower.includes("espécie") || lower.includes("especie") ? "Dinheiro" : undefined;
  const merchant = (text.replace(match[0], "").replace(/\b(pix|crédito|credito|cartão|cartao|débito|debito|dinheiro|espécie|especie|gastei|gasto|paguei|recebo|recebi|ganhei|salário|salario|amanhã|amanha|depois|dia|no|na|em|com|de|do|da|reais|real|fixo|fixa)\b/gi, " ").replace(/\s+/g, " ").trim() || category).slice(0, 80);
  const schedule = scheduleFromText(text);
  return { kind, amountCents, merchant, category, entryDate: schedule.entryDate, isFixed: /\b(fixo|fixa|recorrente|mensal)\b/.test(lower), paymentMethod, isPlanned: schedule.isPlanned || /\b(recebo|vai cair|previsto|prevista)\b/.test(lower), scheduledDay: schedule.scheduledDay };
}

export default function Home() {
  const initial = useMemo(() => readStore() || { items: [], messages: [], profile: { monthlyIncomeCents: 0, savingsGoalCents: 0 } }, []);
  const [items, setItems] = useState<Item[]>(initial.items);
  const [messages, setMessages] = useState<Message[]>(initial.messages);
  const [profile, setProfile] = useState<Profile>(initial.profile);
  const [view, setView] = useState<View>("overview");
  const [chatInput, setChatInput] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const [editItem, setEditItem] = useState<EditItem | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  const [profileOpen, setProfileOpen] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  useEffect(() => saveStore({ items, messages, profile }), [items, messages, profile]);
  useEffect(() => {
    const schedule = profile.salarySchedule;
    if (!schedule || today() < schedule.nextDue) return;
    setProfile((current) => {
      const dueMonth = schedule.nextDue.slice(0, 7);
      const incomeByMonth = { ...(current.incomeByMonth || {}) };
      if (incomeByMonth[dueMonth] === undefined) incomeByMonth[dueMonth] = schedule.amountCents;
      return { ...current, monthlyIncomeCents: schedule.amountCents, incomeByMonth, salarySchedule: { ...schedule, nextDue: nextMonthDate(schedule.nextDue, schedule.day) } };
    });
  }, [profile.salarySchedule?.nextDue]);

    const actualTotals = useMemo(() => items.filter((item) => item.entryDate.slice(0, 7) === today().slice(0, 7)).reduce((acc, item) => { if (item.kind === "income") acc.income += item.amountCents; else { acc.expense += item.amountCents; if (item.isFixed) acc.fixed += item.amountCents; } return acc; }, { income: 0, expense: 0, fixed: 0 }), [items]);
  const monthIncome = profile.incomeByMonth ? (profile.incomeByMonth[currentMonthKey()] ?? 0) : profile.monthlyIncomeCents;
  const totals = { ...actualTotals, plannedIncome: monthIncome, income: actualTotals.income + monthIncome };
  const monthBalance = totals.income - totals.expense;
  const monthStatus = isMonthClosing() && (monthIncome > 0 || actualTotals.income > 0) ? monthBalance >= 0 ? `Fechamento do mês: sobrou ${money(monthBalance)} da sua renda prevista.` : `Atenção: o mês deve fechar ${money(Math.abs(monthBalance))} no vermelho.` : null;
  const categoriesTotal = useMemo(() => Object.entries(items.filter((item) => item.entryDate.slice(0, 7) === today().slice(0, 7) && item.kind !== "income").reduce<Record<string, number>>((acc, item) => { acc[item.category] = (acc[item.category] || 0) + item.amountCents; return acc; }, {})).sort((a, b) => b[1] - a[1]), [items]);
  const recent = [...items].sort((a, b) => b.entryDate.localeCompare(a.entryDate) || b.id - a.id);
  const name = "você";
  function navigate(next: View) { setView(next); setMenuOpen(false); }
  function addItem(item: Omit<Item, "id">) { setItems((current) => [{ ...item, isPlanned: item.isPlanned || item.entryDate > today() || item.kind === "bill", id: Date.now() }, ...current]); setAddOpen(false); }
  function updateItem(changes: Omit<Item, "id">) { if (!editItem) return; setItems((current) => current.map((item) => item.id === editItem.id ? { ...changes, id: editItem.id } : item)); setEditItem(null); }
  function sendChat(event: FormEvent) { event.preventDefault(); const text = chatInput.trim(); if (!text) return; const parsed = parseText(text); let reply = "Posso registrar uma receita, despesa ou conta. Tente: “Pix 10 shopping”, “crédito 34 restaurante” ou “recebi 2500”."; if (/\b(saldo|quanto gastei|gastos|resumo)\b/i.test(text)) reply = `Neste mês: renda prevista ${money(totals.income)}, despesas ${money(totals.expense)}. Seu saldo previsto é ${money(monthBalance)}.`; else if (parsed) { const isSalarySchedule = parsed.kind === "income" && parsed.scheduledDay && /\b(salário|salario)\b/i.test(text); if (isSalarySchedule) { setProfile((current) => ({ ...current, monthlyIncomeCents: 0, incomeByMonth: { ...(current.incomeByMonth || {}), [currentMonthKey()]: 0 }, salarySchedule: { amountCents: parsed.amountCents, day: parsed.scheduledDay!, nextDue: parsed.entryDate } })); reply = `Salário agendado: ${money(parsed.amountCents)} todo dia ${parsed.scheduledDay}. O valor entra automaticamente na renda quando chegar a data prevista.`; } else { addItem(parsed); reply = `${parsed.kind === "income" ? (parsed.isPlanned ? "Receita prevista" : "Receita extra registrada") : parsed.kind === "bill" ? "Conta planejada" : "Gasto registrado"}: ${parsed.merchant} · ${money(parsed.amountCents)}${parsed.paymentMethod ? ` · ${parsed.paymentMethod}` : ""}${parsed.entryDate !== today() ? ` · para ${dateLabel(parsed.entryDate)}` : ""}.`; } } setMessages((current) => [...current, { id: Date.now(), role: "user", content: text }, { id: Date.now() + 1, role: "assistant", content: reply }]); setChatInput(""); setChatOpen(false); }

  return <div className="app-shell">
    <aside className={`sidebar ${menuOpen ? "sidebar-open" : ""}`}><div className="brand-lockup"><img src={logoUrl} alt="" className="brand-mark" /><div><p className="brand-name">Bolso Claro</p><p className="brand-caption">agenda financeira</p></div><button className="mobile-close" onClick={() => setMenuOpen(false)} aria-label="Fechar menu"><X size={18} /></button></div><nav className="main-nav" aria-label="Navegação principal"><NavButton active={view === "overview"} icon={<LayoutDashboard size={18} />} label="Visão geral" onClick={() => navigate("overview")} /><NavButton active={view === "transactions"} icon={<Receipt size={18} />} label="Lançamentos" onClick={() => navigate("transactions")} /><NavButton active={view === "settings"} icon={<Settings2 size={18} />} label="Configurações" onClick={() => navigate("settings")} /></nav><div className="sidebar-spacer" /><div className="sidebar-tip"><div className="tip-icon"><Sparkles size={16} /></div><p><strong>Modo privado</strong><br />Seus dados ficam apenas neste celular, sem conta e sem compartilhamento.</p></div><div className="sidebar-profile"><div className="avatar">VC</div><div className="profile-copy"><strong>Minha agenda</strong><span>armazenamento local</span></div></div></aside>
    {menuOpen && <button className="mobile-overlay" onClick={() => setMenuOpen(false)} aria-label="Fechar menu" />}
    <main className="main-area"><header className="topbar"><div className="topbar-left"><button className="mobile-menu-button" onClick={() => setMenuOpen(true)} aria-label="Abrir menu"><Menu size={20} /></button><div><p className="eyebrow">{monthLabel()}</p><h1>{view === "overview" ? `${greeting()}, ${name}` : view === "transactions" ? "Seus lançamentos" : "Seu espaço financeiro"}</h1></div></div><div className="topbar-actions"><button className="notification-button" onClick={() => setChatOpen(true)} aria-label="Abrir copiloto"><Bell size={18} /></button><button className="top-avatar" onClick={() => setProfileOpen(true)}>VC</button></div></header>
      {view === "overview" && <div className="page-grid"><section className="content-column">{monthStatus && <MonthStatus message={monthStatus} positive={monthBalance >= 0} />}<div className="balance-card"><div className="balance-card-top"><div><p className="card-kicker">Saldo previsto no mês</p><p className="balance-value">{money(monthBalance)}</p></div><div className="balance-badge"><TrendingUp size={14} /> local e privado</div></div><div className="balance-rule" /><div className="balance-footer"><span><ArrowUpRight size={14} /> receitas <strong>{money(totals.income)}</strong></span><span><ArrowDownLeft size={14} /> despesas <strong>{money(totals.expense)}</strong></span></div></div><div className="metrics-grid"><Metric icon={<ArrowUpRight size={17} />} label="Receitas" value={money(totals.income)} accent="green" note="neste mês" /><Metric icon={<ArrowDownLeft size={17} />} label="Despesas" value={money(totals.expense)} accent="orange" note="neste mês" /><Metric icon={<Receipt size={17} />} label="Gastos fixos" value={money(totals.fixed)} accent="purple" note="compromissos" /></div><div className="section-heading"><div><p className="eyebrow">Visão do mês</p><h2>Para onde vai seu dinheiro</h2></div><button className="text-button" onClick={() => navigate("transactions")}>ver lançamentos <ChevronRight size={15} /></button></div><div className="panel category-panel">{categoriesTotal.length ? categoriesTotal.map(([category, total]) => <div className="category-row" key={category}><div className="category-meta"><span className="category-dot" style={{ backgroundColor: categoryColors[category] || categoryColors.Outros }} /><span>{category}</span><strong>{money(total)}</strong></div><div className="category-track"><span style={{ width: `${Math.max(8, (total / categoriesTotal[0][1]) * 100)}%`, backgroundColor: categoryColors[category] || categoryColors.Outros }} /></div></div>) : <EmptyPanel icon={<BarChart3 size={22} />} title="Seu mapa financeiro começa aqui" body="Registre um gasto no chat e suas categorias aparecem neste espaço." />}</div><div className="section-heading compact-heading"><div><p className="eyebrow">Histórico</p><h2>Últimos lançamentos</h2></div><button className="icon-button" onClick={() => setAddOpen(true)} aria-label="Adicionar lançamento"><Plus size={18} /></button></div><div className="panel transaction-panel">{recent.length ? recent.slice(0, 5).map((item) => <TransactionRow key={item.id} item={item} onEdit={() => setEditItem(item)} onDelete={() => setItems((current) => current.filter((entry) => entry.id !== item.id))} />) : <EmptyPanel icon={<Receipt size={22} />} title="Nenhum lançamento ainda" body="Digite algo como “mercado 120” no chat ao lado." />}</div></section><ChatPanel messages={messages} input={chatInput} setInput={setChatInput} onSubmit={sendChat} open={chatOpen} onClose={() => setChatOpen(false)} /></div>}
      {view === "transactions" && <TransactionsView items={recent} onAdd={() => setAddOpen(true)} onEdit={setEditItem} onDelete={(id) => setItems((current) => current.filter((item) => item.id !== id))} />}
      {view === "settings" && <SettingsView profile={profile} onSave={(income, goal) => setProfile((current) => ({ ...current, monthlyIncomeCents: income, savingsGoalCents: goal, incomeByMonth: { ...(current.incomeByMonth || {}), [currentMonthKey()]: income } }))} />}
    </main>
    <button className="chat-fab" onClick={() => setChatOpen(true)} aria-label="Abrir copiloto financeiro"><MessageCircle size={21} /><span>anotar gasto</span></button>
    {editItem && <EditItemModal item={editItem} onClose={() => setEditItem(null)} onSave={updateItem} />} {addOpen && <AddItemModal onClose={() => setAddOpen(false)} onSave={addItem} />} {profileOpen && <Modal title="Sua agenda" onClose={() => setProfileOpen(false)}><div className="profile-modal"><div className="large-avatar">VC</div><h3>Modo privado ativo</h3><p>Seus lançamentos ficam somente neste celular.</p><p className="local-mode-note">Não usamos login nem enviamos seus dados para outra pessoa.</p></div></Modal>}
  </div>;
}

function NavButton({ active, icon, label, onClick }: { active: boolean; icon: ReactNode; label: string; onClick: () => void }) { return <button className={`nav-button ${active ? "active" : ""}`} onClick={onClick}>{icon}<span>{label}</span>{active && <span className="nav-active-dot" />}</button>; }
function Metric({ icon, label, value, accent, note }: { icon: ReactNode; label: string; value: string; accent: string; note: string }) { return <div className="metric-card"><div className={`metric-icon ${accent}`}>{icon}</div><div><p>{label}</p><strong>{value}</strong><span>{note}</span></div></div>; }
function EmptyPanel({ icon, title, body }: { icon: ReactNode; title: string; body: string }) { return <div className="empty-panel"><div className="empty-icon">{icon}</div><strong>{title}</strong><p>{body}</p></div>; }
function TransactionRow({ item, onEdit, onDelete }: { item: Item; onEdit: () => void; onDelete: () => void }) { const income = item.kind === "income"; return <div className="transaction-row"><div className={`transaction-icon ${income ? "income" : "expense"}`}>{income ? <ArrowUpRight size={16} /> : <Receipt size={16} />}</div><div className="transaction-copy"><strong>{item.merchant || item.category}</strong><span>{item.category} · {shortDate(item.entryDate)}{item.isPlanned ? " · previsto" : ""}{item.paymentMethod ? ` · ${item.paymentMethod}` : ""}{item.isFixed ? " · fixo" : ""}</span></div><strong className={`transaction-amount ${income ? "income-text" : ""}`}>{income ? "+" : "-"}{money(item.amountCents)}</strong><button className="icon-button row-action" onClick={onEdit} aria-label="Editar lançamento"><Edit3 size={15} /></button><button className="icon-button row-action danger" onClick={onDelete} aria-label="Excluir lançamento"><Trash2 size={15} /></button></div>; }
function ChatPanel({ messages, input, setInput, onSubmit, open, onClose }: { messages: Message[]; input: string; setInput: (value: string) => void; onSubmit: (event: FormEvent) => void; open: boolean; onClose: () => void }) { const suggestions = ["Pix 10 shopping", "salário 1654 dia 5", "quanto gastei esse mês?"]; return <section className={`chat-panel ${open ? "chat-open" : ""}`}><div className="chat-header"><div className="chat-title"><div className="chat-orb"><Sparkles size={17} /></div><div><strong>Seu copiloto financeiro</strong><span>funciona sem sair do celular</span></div></div><button className="chat-close" onClick={onClose} aria-label="Fechar copiloto"><X size={17} /></button></div><div className="chat-body">{!messages.length ? <div className="chat-welcome"><div className="welcome-mark"><MessageCircle size={24} /></div><h3>Me conta, o que aconteceu?</h3><p>Registre um gasto, uma receita ou pergunte sobre sua vida financeira.</p><div className="suggestion-list">{suggestions.map((suggestion) => <button key={suggestion} onClick={() => setInput(suggestion)}>{suggestion}<ChevronRight size={14} /></button>)}</div></div> : <div className="message-list">{messages.map((message) => <div className={`message-row ${message.role === "user" ? "user-message" : "assistant-message"}`} key={message.id}><div className="message-avatar">{message.role === "user" ? "VC" : <Sparkles size={13} />}</div><div className="message-bubble">{message.content}</div></div>)}</div>}</div><form className="chat-composer" onSubmit={onSubmit}><textarea value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ex.: mercado 120 no débito" rows={1} /><button type="submit" className="send-button" disabled={!input.trim()}><Send size={17} /></button></form></section>; }
function MonthStatus({ message, positive }: { message: string; positive: boolean }) { return <div className={`month-status ${positive ? "positive" : "negative"}`}><div className="info-icon">{positive ? <Check size={17} /> : <CircleAlert size={17} />}</div><div><strong>{positive ? "Boa notícia" : "Atenção ao seu orçamento"}</strong><p>{message}</p></div></div>; }
function TransactionsView({ items, onAdd, onEdit, onDelete }: { items: Item[]; onAdd: () => void; onEdit: (item: Item) => void; onDelete: (id: number) => void }) { return <section className="full-page"><div className="section-heading page-heading"><div><p className="eyebrow">Registro completo</p><h2>Todos os lançamentos</h2></div><button onClick={onAdd} className="primary-button"><Plus size={17} /> adicionar</button></div><div className="panel transaction-panel large-panel">{items.length ? items.map((item) => <TransactionRow key={item.id} item={item} onEdit={() => onEdit(item)} onDelete={() => onDelete(item.id)} />) : <EmptyPanel icon={<Receipt size={22} />} title="Sua lista está vazia" body="Use o chat ou adicione seu primeiro lançamento." />}</div><div className="info-strip"><div className="info-icon"><CircleDollarSign size={18} /></div><div><strong>Privacidade por padrão</strong><p>Este aparelho guarda seus dados no navegador. Outra pessoa usando outro celular terá uma agenda separada.</p></div></div></section>; }
function SettingsView({ profile, onSave }: { profile: Profile; onSave: (income: number, goal: number) => void }) { const currentIncome = profile.incomeByMonth ? (profile.incomeByMonth[currentMonthKey()] ?? 0) : profile.monthlyIncomeCents; const [income, setIncome] = useState((currentIncome / 100).toFixed(2).replace(".", ",")); const [goal, setGoal] = useState((profile.savingsGoalCents / 100).toFixed(2).replace(".", ",")); return <section className="full-page settings-page"><div className="section-heading page-heading"><div><p className="eyebrow">Seu espaço financeiro</p><h2>Configurações simples</h2></div></div><div className="settings-grid"><form className="panel settings-card" onSubmit={(event) => { event.preventDefault(); onSave(parseMoney(income), parseMoney(goal)); }}><div className="settings-card-title"><div className="metric-icon green"><WalletCards size={18} /></div><div><h3>Renda prevista deste mês</h3><p>Você pode alterar este valor a cada mês. Um mês não altera o outro.</p></div></div><label><span>Renda de {monthLabel()}</span><div className="input-with-prefix"><small>R$</small><input value={income} onChange={(event) => setIncome(event.target.value)} placeholder="0,00" /></div></label><label><span>Meta de economia mensal <small>(opcional)</small></span><div className="input-with-prefix"><small>R$</small><input value={goal} onChange={(event) => setGoal(event.target.value)} placeholder="0,00" /></div></label><button type="submit" className="primary-button"><Check size={16} /> salvar informações</button></form><div className="panel settings-card"><div className="settings-card-title"><div className="metric-icon purple"><CreditCard size={18} /></div><div><h3>Armazenamento</h3><p>Sem login, sem nuvem e sem compartilhamento.</p></div></div><div className="method-placeholder"><CreditCard size={17} /><span>Use “Pix 10 shopping”, “crédito 34 restaurante” ou “25 dinheiro gasolina”. O chat identifica a forma de pagamento e a categoria.</span></div></div></div></section>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal-card"><div className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Fechar"><X size={18} /></button></div>{children}</div></div>; }
function EditItemModal({ item, onClose, onSave }: { item: Item; onClose: () => void; onSave: (item: Omit<Item, "id">) => void }) { return <ItemForm title="Editar lançamento" initial={item} onClose={onClose} onSave={onSave} />; }
function AddItemModal({ onClose, onSave }: { onClose: () => void; onSave: (item: Omit<Item, "id">) => void }) { return <ItemForm title="Novo lançamento" initial={{ kind: "expense", amountCents: 0, merchant: "", category: "Outros", entryDate: today(), isFixed: false, paymentMethod: undefined, isPlanned: false }} onClose={onClose} onSave={onSave} />; }
function ItemForm({ title, initial, onClose, onSave }: { title: string; initial: Omit<Item, "id">; onClose: () => void; onSave: (item: Omit<Item, "id">) => void }) { const [item, setItem] = useState(initial); const [amount, setAmount] = useState(initial.amountCents ? (initial.amountCents / 100).toFixed(2).replace(".", ",") : ""); return <Modal title={title} onClose={onClose}><form className="modal-form" onSubmit={(event) => { event.preventDefault(); if (!item.merchant.trim() || !parseMoney(amount)) return; onSave({ ...item, amountCents: parseMoney(amount), isPlanned: item.isPlanned || item.entryDate > today() || item.kind === "bill" }); }}><div className="segmented-control">{([["expense", "Despesa"], ["income", "Receita"], ["bill", "Conta"]] as [Kind, string][]).map(([value, label]) => <button type="button" key={value} className={item.kind === value ? "selected" : ""} onClick={() => setItem({ ...item, kind: value })}>{label}</button>)}</div><label><span>Nome</span><input value={item.merchant} onChange={(event) => setItem({ ...item, merchant: event.target.value })} placeholder="Ex.: Mercado" required /></label><label><span>Categoria</span><select value={item.category} onChange={(event) => setItem({ ...item, category: event.target.value })}>{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label><span>Forma de pagamento</span><select value={item.paymentMethod || ""} onChange={(event) => setItem({ ...item, paymentMethod: event.target.value || undefined })}><option value="">Não informado</option>{paymentMethods.map((method) => <option key={method}>{method}</option>)}</select></label><div className="form-row"><label><span>Valor</span><div className="input-with-prefix"><small>R$</small><input value={amount} onChange={(event) => setAmount(event.target.value)} placeholder="0,00" required /></div></label><label><span>Data</span><input type="date" value={item.entryDate} onChange={(event) => setItem({ ...item, entryDate: event.target.value })} required /></label></div><label className="checkbox-line"><input type="checkbox" checked={item.isFixed} onChange={(event) => setItem({ ...item, isFixed: event.target.checked })} /><span>É fixo ou recorrente</span></label><div className="modal-actions"><button type="button" className="outline-button" onClick={onClose}>cancelar</button><button type="submit" className="primary-button">salvar</button></div></form></Modal>; }
